apiVersion: v1
kind: Service
metadata:
  name: {{ include "mymicroserviceapp.fullname" . }}
  labels:
    {{- include "mymicroserviceapp.labels" . | nindent 4 }}
  annotations:
  a8r.io/owner: "@baziwane"
  a8r.io/description: ".Net 5.0 Web Api microservice application"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mymicroserviceapp.selectorLabels" . | nindent 4 }}
